-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, 
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender
ORDER BY revenue DESC;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
    customer_id, 
    purchase_amount 
FROM customer 
WHERE LOWER(TRIM(discount_applied)) = 'yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC;


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY "Average Product Rating" DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(100.0 * COUNT(*) FILTER (WHERE LOWER(TRIM(discount_applied)) = 'yes') / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS total_customers 
FROM customer_type 
GROUP BY customer_segment
ORDER BY total_customers DESC;


-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;
 

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers,
    ROUND(100.0 * COUNT(customer_id) / SUM(COUNT(customer_id)) OVER(), 2) AS pct_of_repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;